### ISSUE TITLE
virtio-fs driver: why spin on `InHeader.unique` pointer

### ISSUE THREAD

**Issue by dimakuv** [torokernel/torokernel#454]
You have the following code in your Virtio-FS implementation:

https://github.com/torokernel/torokernel/blob/24b9eeede11f0a92de20ec6a9c5e5e209beb29ce/rtl/drivers/VirtIOFS.pas#L567-L568

After you submit this FUSE request on a virtqueue, you need to wait for the response from the host. For this, you do the following:

https://github.com/torokernel/torokernel/blob/24b9eeede11f0a92de20ec6a9c5e5e209beb29ce/rtl/drivers/VirtIOFS.pas#L583-L584

I read through the virtio-fs documentation (including the latest draft of the "Virtual I/O Device (VIRTIO) Version 1.1;
Committee Specification 01" document). I couldn't find anywhere that this is a legitimate or advised way of waiting for a request completion by the guest VM. I'm surprised that this works at all.

Why did you implement such a notification mechanism? Why does it work? What guarantees that `InHeader.unique` pointer will be updated by the host? Am I missing some part of your Torokernel code that ensures that `InHeader.unique` becomes `True` on request completion?

Thanks in advance! Just looking at your virtio-fs code for inspiration. The rest of the code is clear to me, but this part I don't get.

**Comment by MatiasVara** [comment]
Hello! I agree the code is not clear, thanks for spotting it! The following is the interruption handler for virtio-fs:
https://github.com/torokernel/torokernel/blob/24b9eeede11f0a92de20ec6a9c5e5e209beb29ce/rtl/drivers/VirtIOFS.pas#L609 
As you already know, after the host consumes the buffer from the avail ring, it puts it in the used ring and triggers an interruption. Then, the handler just uses the information in unique as a pointer to a boolean and makes it true. This makes the code to exit the loop. Also, the current waiting mechanism does not block, instead, it just waits until the operation is done. This is a sort of optimization to prevent the thread to go to sleep until completion. However, I never really measured it so I am not sure if it is an actual improvement.

**Comment by dimakuv** [comment]
@MatiasVara Thanks for the quick reply!

So this function: https://github.com/torokernel/torokernel/blob/24b9eeede11f0a92de20ec6a9c5e5e209beb29ce/rtl/drivers/VirtIOFS.pas#L597

is actually an interrupt handler, right?

I see this code: https://github.com/torokernel/torokernel/blob/24b9eeede11f0a92de20ec6a9c5e5e209beb29ce/rtl/drivers/VirtIOFS.pas#L633-L636

So this code installs the `VirtIOProcessQueue()` procedure as a callback invoked on every interrupt coming on the virtio-fs specific IRQ. Is my understanding correct?

If my understanding is correct, then I got it. This `VirtIOProcessQueue()` interrupt handler was a missing piece. I didn't look closer at it and didn't take into account that the IRQ is added to the APIC table.

**Comment by MatiasVara** [comment]
> @MatiasVara Thanks for the quick reply!
> 
> So this function:
> 
> https://github.com/torokernel/torokernel/blob/24b9eeede11f0a92de20ec6a9c5e5e209beb29ce/rtl/drivers/VirtIOFS.pas#L597
> 
> is actually an interrupt handler, right?

Yes, it is. 

> 
> I see this code:
> 
> https://github.com/torokernel/torokernel/blob/24b9eeede11f0a92de20ec6a9c5e5e209beb29ce/rtl/drivers/VirtIOFS.pas#L633-L636
> 
> So this code installs the `VirtIOProcessQueue()` procedure as a callback invoked on every interrupt coming on the virtio-fs specific IRQ. Is my understanding correct?
> 

Yes, it is. Most of the work happens in VirtIO.pas. In that unit, IRQs are handled and then the correct callback is invoked.  

> If my understanding is correct, then I got it. This `VirtIOProcessQueue()` interrupt handler was a missing piece. I didn't look closer at it and didn't take into account that the IRQ is added to the APIC table.
